# Generated by Django 3.1.4 on 2021-01-30 05:58

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code_error', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='department', on_delete=django.db.models.deletion.CASCADE, to='events.codeerror')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.department')),
            ],
        ),
        migrations.AddField(
            model_name='codeerror',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.department'),
        ),
    ]
