# Generated by Django 3.1.4 on 2021-01-31 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0004_auto_20210124_0125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('close', 'Kết Thúc'), ('complete', 'Hoàn Thành'), ('process', 'Đang Xử Lý')], default='new', max_length=20)),
                ('status_atm', models.CharField(choices=[('in_services', 'In Services'), ('out_services', 'Out Of Services'), ('offline', 'Offline')], default='out_services', max_length=20)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_complete', models.DateTimeField(auto_now=True)),
                ('date_post', models.DateTimeField(auto_now=True)),
                ('date_close', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Bình Thường'), ('high', 'Cao')], default='medium', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.error')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atms.atm')),
            ],
        ),
    ]
