# Generated by Django 3.1.4 on 2021-02-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210131_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='status',
            field=models.CharField(choices=[('in_services', 'In Services'), ('out_services', 'Out Of Services'), ('offline', 'Offline')], default='out_services', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('new', 'Mới'), ('process', 'Đang Xử Lý'), ('complete', 'Hoàn Thành'), ('close', 'Kết Thúc')], default='new', max_length=20),
        ),
    ]
