# Generated by Django 3.1.4 on 2021-02-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_error_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='supervisor_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
