# Generated by Django 3.1.4 on 2021-02-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210216_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='report24h',
            field=models.BooleanField(default=False),
        ),
    ]
