# Generated by Django 3.1.4 on 2021-04-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210218_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='event_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.event'),
        ),
    ]
