# Generated by Django 3.1.4 on 2021-07-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20210623_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200)),
                ('atm_name', models.CharField(max_length=200)),
                ('terminal_id', models.CharField(max_length=10)),
                ('atm_sum', models.IntegerField(blank=True, null=True)),
                ('surcharge_sum', models.IntegerField(blank=True, null=True)),
                ('napas_sum', models.IntegerField(blank=True, null=True)),
                ('fee_sum', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
