# Generated by Django 3.1.4 on 2021-01-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_location_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_vynamic', models.CharField(max_length=100)),
                ('name_way4', models.CharField(max_length=200)),
                ('terminal_id', models.CharField(max_length=20)),
                ('machine_no', models.CharField(max_length=20)),
                ('gateway', models.IntegerField()),
                ('ip', models.IntegerField()),
                ('camera_ip', models.IntegerField()),
                ('date_setup', models.DateTimeField(blank=True, null=True)),
                ('date_operate', models.DateTimeField(blank=True, null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, null=True)),
                ('ghost_vesion', models.CharField(max_length=30)),
                ('security_soft', models.CharField(choices=[('ts', 'Terminal Security'), ('s', 'Symantec')], max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
    ]
