# Generated by Django 3.1.4 on 2021-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0002_auto_20210124_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='status',
            field=models.CharField(blank=True, choices=[('hd', 'Hoạt Động'), ('nhd', 'Ngưng Hoạt Động'), ('ld', 'Lắp Đặt')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='ghost_vesion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='machine_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='name_vynamic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='name_way4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='security_soft',
            field=models.CharField(blank=True, choices=[('ts', 'Terminal Security'), ('s', 'Symantec')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='terminal_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
