# Generated by Django 3.1.4 on 2021-01-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0003_auto_20210124_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='status',
            field=models.CharField(choices=[('hd', 'Hoạt Động'), ('nhd', 'Ngưng Hoạt Động'), ('ld', 'Lắp Đặt')], default='hd', max_length=20),
        ),
    ]
