# Generated by Django 3.1.4 on 2021-01-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210114_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(blank=True, choices=[('nhd', 'Ngưng Hoạt Động'), ('hd', 'Hoạt Động')], default='hd', max_length=20, null=True),
        ),
    ]
